Creating Arrays with Numpy (different ways)

In [3]:
import numpy as np
arr = np.array([10,20,30,15,40])
print(arr)

[10 20 30 15 40]


In [5]:
b =list(range(2,21,3))
print(b,type(b),sep='\n')
arr1 =np.array(b)
print(arr1,type(arr1),sep='\n')


[2, 5, 8, 11, 14, 17, 20]
<class 'list'>
[ 2  5  8 11 14 17 20]
<class 'numpy.ndarray'>


In [7]:
c = list('numpy')
arr2=np.array(c)
print(arr2)

['n' 'u' 'm' 'p' 'y']


In [11]:
arr3 =np.array(range(10),float)
print(arr3)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
arr4 = arr3.reshape(2,5)#converting to 2D array
print(arr4)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [21]:
print('arr3 is {} array and its shape is {}'.format(arr3.ndim,arr3.shape))
print('arr4 is {} array and its shape is {}'.format(arr4.ndim,arr4.shape))

arr3 is 1 array and its shape is (10,)
arr4 is 2 array and its shape is (2, 5)


Arthmetical operation on array

In [29]:
A = np.array(range(10))
B = np.array(range(0,20,2))
print(A,B,sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [30]:
print(np.add(A,B))#addition of arrays

[ 0  3  6  9 12 15 18 21 24 27]


In [31]:
print(np.subtract(A,B))#subtraction of arrays

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [32]:
print(np.multiply(A,B))#product of arrays

[  0   2   8  18  32  50  72  98 128 162]


In [35]:
print(np.divide(A[1:],B[1:]))#division of arrays 

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [40]:
print(np.power(A[1:5],B[1:5]))#A**B 

[    1    16   729 65536]


Indexing and Slicing

In [43]:
print(B)

[ 0  2  4  6  8 10 12 14 16 18]


In [44]:
print(B[-1])#print last element

18


In [45]:
print(B[2])#print third element

4


In [47]:
print(B[:3])# print first three elements

[0 2 4]


In [49]:
print(B[-3:])# print last three elements

[14 16 18]


In [50]:
print(B[1:4])#print second element to forth element

[2 4 6]


In [51]:
print(B[::2])#print every second element

[ 0  4  8 12 16]


In [52]:
print(B[::-1])#print array in reverse order

[18 16 14 12 10  8  6  4  2  0]


Shape and Reshare the arrays

In [63]:
C = np.array([2,4,5,8,9,10,30,3,1,10,12,12])
print(C, C.shape)
C.shape =(4,3)# changing 1D array to 2D array
print(C,C.shape)

[ 2  4  5  8  9 10 30  3  1 10 12 12] (12,)
[[ 2  4  5]
 [ 8  9 10]
 [30  3  1]
 [10 12 12]] (4, 3)


In [74]:
print(np.reshape(C,(3,2,2)))# changing to 3D


[[[ 2  4]
  [ 5  8]]

 [[ 9 10]
  [30  3]]

 [[ 1 10]
  [12 12]]]


In [70]:
print(C.reshape(-1))# changing back to 1D

[ 2  4  5  8  9 10 30  3  1 10 12 12]


Specail Arrays

In [79]:
arr =np.zeros(4,int)#1D array of four elements with zeros
print(arr)

[0 0 0 0]


In [80]:
arr =np.zeros((2,2),int)#2D array of four elements with zeros
print(arr)

[[0 0]
 [0 0]]


In [81]:
arr1 =np.ones(4)#1D array of four elements with ones and default data type float
print(arr1)

[1. 1. 1. 1.]


In [84]:
print(np.identity(3,int))#3x3 identity matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [90]:
print(np.eye(3,k=-1))#creating 1s below diagonal
print(np.eye(3,k=1))#creating 1s above diagonal
print(np.eye(3))#creating 1s on diagonal by default

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array functions - mean, variance, standard deviation, maximum, minimum etc

In [93]:
Arr = np.array([1,5,10,15,20,25,30])
print(Arr.mean())# finding mean of the array
print(np.round(Arr.mean(), decimals =3))#rounding the result to 3 decimal points

15.142857142857142
15.143


In [94]:
print(Arr.var())#finding variance of the array
print(np.ceil(Arr.var()))#roundind the result to hightest integer

95.83673469387756
96.0


In [95]:
print(Arr.std())#finding standard deviation of the array
print(np.floor(Arr.std()))#roundind the result to lowest integer

9.789623828006752
9.0


In [98]:
print(max(Arr))#maximum value of the array
print(min(Arr))#minimum value of the array
print(sum(Arr))#sum of the array

30
1
106
